### ISSUE TITLE
Add Social media meta tags

### ISSUE THREAD

**Issue by patak-cat** [kevcodez/intheloop#2]
Consider including social media meta tags, so the links are expanded when shared in twitter, reddit, discord, etc
https://css-tricks.com/essential-meta-tags-social-media/

Example from https://patak.dev/web/vite-2.html
And how it looks expanded in a tweet: https://twitter.com/patak_js/status/1349713992122560512

```html
    <meta name="description" content="A VitePress powered post about Vite 2 and the importance of the instant feedback loop that it enables">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:url" content="https://www.patak.dev/web/vite-2.html">
    <meta name="twitter:title" content="Vite 2">
    <meta name="twitter:description" content="A VitePress powered post about Vite 2 and the importance of the instant feedback loop that it enables">
    <meta name="twitter:creator" content="@patak_js">
    <meta name="twitter:image" content="https://www.patak.dev/images/vite-2.jpg">
```

**Comment by kevcodez** [comment]
Haven't invested a single second in SEO, social media and other tags and structured data yet, but I do agree that this should be included!

When Nuxt V3 finally hits, I will upgrade to Nuxt 3 + Vite, this will be neater to implement.

With Vue 3 teleport it should be fairly simple to implement in the SPA though - there should be a Vue 3 package for this

**Comment by kevcodez** [comment]
I actually migrated to Nuxt (who knows when V3 will finally hit) to support this
